export const popularCities = [
    "Hyderabad",
    "Bangalore",
    "Chennai",
    "Goa",
    "Vijayawada",
    "Nellore",
    "Jaipur",
    "Mangalore",
    "Visakhapatnam",
    "Delhi",
    "Indore",
    "Kolkata",
  ];


export const cityDropPoints = [
  { id: 1, city: "Mumbai", dropPoint: "Andheri Metro Station" },
  { id: 2, city: "Mumbai", dropPoint: "Bandra Station" },
  { id: 3, city: "Mumbai", dropPoint: "Dadar Circle" },
  { id: 4, city: "Delhi", dropPoint: "Connaught Place" },
  { id: 5, city: "Delhi", dropPoint: "Kashmere Gate" },
  { id: 6, city: "Delhi", dropPoint: "Saket Mall" },
  { id: 7, city: "Bangalore", dropPoint: "MG Road Metro" },
  { id: 8, city: "Bangalore", dropPoint: "Majestic Bus Stand" },
  { id: 9, city: "Bangalore", dropPoint: "Electronic City" },
  { id: 10, city: "Hyderabad", dropPoint: "Gachibowli" },
  { id: 11, city: "Hyderabad", dropPoint: "Hitech City" },
  { id: 12, city: "Hyderabad", dropPoint: "Charminar" },
  { id: 13, city: "Chennai", dropPoint: "T Nagar" },
  { id: 14, city: "Chennai", dropPoint: "Marina Beach" },
  { id: 15, city: "Chennai", dropPoint: "Guindy" },
  { id: 16, city: "Kolkata", dropPoint: "Howrah Bridge" },
  { id: 17, city: "Kolkata", dropPoint: "Park Street" },
  { id: 18, city: "Kolkata", dropPoint: "Salt Lake Sector V" },
  { id: 19, city: "Pune", dropPoint: "Shivaji Nagar" },
  { id: 20, city: "Pune", dropPoint: "Viman Nagar" },
  { id: 21, city: "Pune", dropPoint: "Kothrud" },
  { id: 22, city: "Ahmedabad", dropPoint: "Navrangpura" },
  { id: 23, city: "Ahmedabad", dropPoint: "SG Highway" },
  { id: 24, city: "Ahmedabad", dropPoint: "Maninagar" },
  { id: 25, city: "Jaipur", dropPoint: "MI Road" },
  { id: 26, city: "Jaipur", dropPoint: "Hawa Mahal" },
  { id: 27, city: "Jaipur", dropPoint: "Malviya Nagar" },
  { id: 28, city: "Surat", dropPoint: "Adajan" },
  { id: 29, city: "Surat", dropPoint: "Varachha" },
  { id: 30, city: "Surat", dropPoint: "Vesu" },
  { id: 31, city: "Lucknow", dropPoint: "Hazratganj" },
  { id: 32, city: "Lucknow", dropPoint: "Gomti Nagar" },
  { id: 33, city: "Lucknow", dropPoint: "Charbagh" },
  { id: 34, city: "Indore", dropPoint: "Rajwada" },
  { id: 35, city: "Indore", dropPoint: "Vijay Nagar" },
  { id: 36, city: "Indore", dropPoint: "Palasia" },
  { id: 37, city: "Goa", dropPoint: "Calangute" },
  { id: 38, city: "Goa", dropPoint: "Baga Beach" },
  { id: 39, city: "Goa", dropPoint: "Panaji" },
  { id: 40, city: "Nagpur", dropPoint: "Sitabuldi" },
  { id: 41, city: "Nagpur", dropPoint: "Dharampeth" },
  { id: 42, city: "Nagpur", dropPoint: "Civil Lines" },
  { id: 43, city: "Kanpur", dropPoint: "Mall Road" },
  { id: 44, city: "Kanpur", dropPoint: "Swaroop Nagar" },
  { id: 45, city: "Kanpur", dropPoint: "Barra" },
  { id: 46, city: "Patna", dropPoint: "Kankarbagh" },
  { id: 47, city: "Patna", dropPoint: "Patliputra" },
  { id: 48, city: "Patna", dropPoint: "Bailey Road" },
  { id: 49, city: "Bhopal", dropPoint: "MP Nagar" },
  { id: 50, city: "Bhopal", dropPoint: "Arera Colony" },
  { id: 51, city: "Bhopal", dropPoint: "New Market" },
  { id: 52, city: "Coimbatore", dropPoint: "Gandhipuram" },
  { id: 53, city: "Coimbatore", dropPoint: "RS Puram" },
  { id: 54, city: "Coimbatore", dropPoint: "Peelamedu" },
  { id: 55, city: "Mangalore", dropPoint: "Hampankatta" },
  { id: 56, city: "Mangalore", dropPoint: "Bejai" },
  { id: 57, city: "Mangalore", dropPoint: "Kadri" },
  { id: 58, city: "Vijayawada", dropPoint: "Benz Circle" },
  { id: 59, city: "Vijayawada", dropPoint: "Governorpet" },
  { id: 60, city: "Vijayawada", dropPoint: "Labbipet" },
  { id: 61, city: "Visakhapatnam", dropPoint: "MVP Colony" },
  { id: 62, city: "Visakhapatnam", dropPoint: "Dwaraka Nagar" },
  { id: 63, city: "Visakhapatnam", dropPoint: "Gajuwaka" },
  { id: 64, city: "Thiruvananthapuram", dropPoint: "Kazhakoottam" },
  { id: 65, city: "Thiruvananthapuram", dropPoint: "Palayam" },
  { id: 66, city: "Thiruvananthapuram", dropPoint: "Technopark" },
  { id: 67, city: "Kochi", dropPoint: "Edappally" },
  { id: 68, city: "Kochi", dropPoint: "Marine Drive" },
  { id: 69, city: "Kochi", dropPoint: "Fort Kochi" },
  { id: 70, city: "Chandigarh", dropPoint: "Sector 17" },
  { id: 71, city: "Chandigarh", dropPoint: "Sector 22" },
  { id: 72, city: "Chandigarh", dropPoint: "Manimajra" },
  { id: 73, city: "Gurgaon", dropPoint: "Cyber Hub" },
  { id: 74, city: "Gurgaon", dropPoint: "MG Road" },
  { id: 75, city: "Gurgaon", dropPoint: "Sector 29" },
  { id: 76, city: "Noida", dropPoint: "Sector 18" },
  { id: 77, city: "Noida", dropPoint: "Sector 62" },
  { id: 78, city: "Noida", dropPoint: "Botanical Garden Metro" },
  { id: 79, city: "Faridabad", dropPoint: "Badkhal" },
  { id: 80, city: "Faridabad", dropPoint: "NIT Faridabad" },
  { id: 81, city: "Faridabad", dropPoint: "Sector 15" },
  { id: 82, city: "Ludhiana", dropPoint: "Model Town" },
  { id: 83, city: "Ludhiana", dropPoint: "Civil Lines" },
  { id: 84, city: "Ludhiana", dropPoint: "Sarabha Nagar" },
  { id: 85, city: "Guwahati", dropPoint: "Paltan Bazaar" },
  { id: 86, city: "Guwahati", dropPoint: "Six Mile" },
  { id: 87, city: "Guwahati", dropPoint: "Zoo Road" },
  { id: 88, city: "Ranchi", dropPoint: "Main Road" },
  { id: 89, city: "Ranchi", dropPoint: "Harmu" },
  { id: 90, city: "Ranchi", dropPoint: "Lalpur Chowk" },
  { id: 91, city: "Bhubaneswar", dropPoint: "Master Canteen" },
  { id: 92, city: "Bhubaneswar", dropPoint: "Patia" },
  { id: 93, city: "Bhubaneswar", dropPoint: "Saheed Nagar" },
  { id: 94, city: "Mysore", dropPoint: "Vijayanagar" },
  { id: 95, city: "Mysore", dropPoint: "KR Circle" },
  { id: 96, city: "Mysore", dropPoint: "Jayalakshmipuram" },
  { id: 97, city: "Jodhpur", dropPoint: "Raika Bagh" },
  { id: 98, city: "Jodhpur", dropPoint: "Sardarpura" },
  { id: 99, city: "Jodhpur", dropPoint: "Shastri Circle" },
  { id: 100, city: "Udaipur", dropPoint: "Fateh Sagar Lake" }
];

