export const busData = [
  {
    id: "1",
    name: "Perera Travels",
    type: "A/C Sleeper (2+2)",
    time: "9:00 AM — 9:45 AM",
    seatsLeft: 15,
    price: "LKR 200",
    duration: "45 Min",
  },
  {
    id: "2",
    name: "Gayan Express",
    type: "A/C Seater (2+2)",
    time: "10:15 AM — 11:00 AM",
    seatsLeft: 8,
    price: "LKR 220",
    duration: "45 Min",
  },
  {
    id: "3",
    name: "Shehan Travels",
    type: "Non A/C Sleeper (2+1)",
    time: "11:30 AM — 12:15 PM",
    seatsLeft: 5,
    price: "LKR 180",
    duration: "45 Min",
  },
  {
    id: "4",
    name: "Royal Transit",
    type: "A/C Luxury (2+2)",
    time: "12:00 PM — 12:40 PM",
    seatsLeft: 12,
    price: "LKR 300",
    duration: "40 Min",
  },
  {
    id: "5",
    name: "City Line Travels",
    type: "Non A/C Seater (3+2)",
    time: "01:00 PM — 02:00 PM",
    seatsLeft: 20,
    price: "LKR 150",
    duration: "60 Min",
  },
  {
    id: "6",
    name: "Blue Hill Express",
    type: "A/C Premium (2+1)",
    time: "02:30 PM — 03:10 PM",
    seatsLeft: 9,
    price: "LKR 260",
    duration: "40 Min",
  },
  {
    id: "7",
    name: "Super Lanka Travels",
    type: "Non A/C Sleeper (2+1)",
    time: "03:45 PM — 04:30 PM",
    seatsLeft: 6,
    price: "LKR 170",
    duration: "45 Min",
  },
  {
    id: "8",
    name: "Modern Bus Service",
    type: "A/C Seater (2+2)",
    time: "04:00 PM — 04:50 PM",
    seatsLeft: 3,
    price: "LKR 210",
    duration: "50 Min",
  },
  {
    id: "9",
    name: "Sunrise Express",
    type: "A/C Sleeper (2+1)",
    time: "05:00 PM — 05:35 PM",
    seatsLeft: 10,
    price: "LKR 240",
    duration: "35 Min",
  },
  {
    id: "10",
    name: "National Transport",
    type: "Non A/C Seater (3+2)",
    time: "06:30 PM — 07:10 PM",
    seatsLeft: 18,
    price: "LKR 160",
    duration: "40 Min",
  },
];
